apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - django
  - fastapi
  - kong
  - celery-worker-django
  - celery-beat
  - celery-worker-fastapi
  - kafka-consumer
  - celery-exporter-django
  - celery-exporter-fastapi
