apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fastapi-secrets
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: local-secret-store
    kind: SecretStore
  target:
    name: fastapi-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef: { key: fastapi-secrets-source, property: DATABASE_URL }
    - secretKey: REDIS_URL
      remoteRef: { key: fastapi-secrets-source, property: REDIS_URL }
    - secretKey: CELERY_BROKER_URL
      remoteRef: { key: fastapi-secrets-source, property: CELERY_BROKER_URL }
    - secretKey: CELERY_RESULT_BACKEND
      remoteRef: { key: fastapi-secrets-source, property: CELERY_RESULT_BACKEND }
    - secretKey: JWT_PUBLIC_KEY
      remoteRef: { key: fastapi-secrets-source, property: JWT_PUBLIC_KEY }
    - secretKey: KAFKA_BOOTSTRAP_SERVERS
      remoteRef: { key: fastapi-secrets-source, property: KAFKA_BOOTSTRAP_SERVERS }
    - secretKey: ELASTICSEARCH_PASSWORD
      remoteRef: { key: fastapi-secrets-source, property: ELASTICSEARCH_PASSWORD }
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef: { key: fastapi-secrets-source, property: AWS_ACCESS_KEY_ID }
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef: { key: fastapi-secrets-source, property: AWS_SECRET_ACCESS_KEY }
    - secretKey: GITHUB_APP_PRIVATE_KEY
      remoteRef: { key: fastapi-secrets-source, property: GITHUB_APP_PRIVATE_KEY }
    - secretKey: GITHUB_WEBHOOK_SECRET
      remoteRef: { key: fastapi-secrets-source, property: GITHUB_WEBHOOK_SECRET }
    - secretKey: GEMINI_API_KEY
      remoteRef: { key: fastapi-secrets-source, property: GEMINI_API_KEY }
    - secretKey: LANGCHAIN_API_KEY
      remoteRef: { key: fastapi-secrets-source, property: LANGCHAIN_API_KEY }