apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: app
data:
  APP_ENV: "development"
  DEBUG: "true"
  DATABASE_URL: "postgresql+asyncpg://neuralops_fastapi:fastapi_password@fastapi-db.data.svc.cluster.local:5432/neuralops_fastapi_db"
  REDIS_URL: "redis://redis.data.svc.cluster.local:6379/1"
  CELERY_BROKER_URL: "redis://redis.data.svc.cluster.local:6379/2"
  CELERY_RESULT_BACKEND: "redis://redis.data.svc.cluster.local:6379/2"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-kafka-bootstrap.data.svc.cluster.local:9092"
  ELASTICSEARCH_HOSTS: '["https://es-local-es-http.data.svc:9200"]'
  ELASTICSEARCH_CA_CERT_PATH: "/etc/ssl/es/es-ca.crt"
  AWS_S3_ENDPOINT_URL: "http://minio.data.svc.cluster.local:9000"
