apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-exporter-fastapi
  namespace: app
spec:
  template:
    spec:
      containers:
        - name: celery-exporter
          env:
            - name: CE_BROKER_URL
              value: "redis://neuralops-redis.djvi8t.0001.aps1.cache.amazonaws.com:6379/2"
