# -- Debezium Connect ---------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium
  namespace: data
spec:
  replicas: 1
  selector:
    matchLabels: { app: debezium }
  template:
    metadata:
      labels: { app: debezium }
    spec:
      enableServiceLinks: false
      containers:
        - name: debezium
          image: debezium/connect:2.7.0.Final
          env:
            - { name: KAFKA_HEAP_OPTS, value: "-Xms256m -Xmx512m" }
            - { name: BOOTSTRAP_SERVERS, value: "kafka-kafka-bootstrap.data.svc.cluster.local:9092" }
            - { name: GROUP_ID, value: "debezium-django-db1" }
            - { name: CONFIG_STORAGE_TOPIC, value: "debezium_configs" }
            - { name: OFFSET_STORAGE_TOPIC, value: "debezium_offsets" }
            - { name: STATUS_STORAGE_TOPIC, value: "debezium_status" }
            - { name: CONFIG_STORAGE_REPLICATION_FACTOR, value: "1" }
            - { name: OFFSET_STORAGE_REPLICATION_FACTOR, value: "1" }
            - { name: STATUS_STORAGE_REPLICATION_FACTOR, value: "1" }
          ports:
            - containerPort: 8083
              name: api
---
apiVersion: v1
kind: Service
metadata:
  name: debezium
  namespace: data
spec:
  ports:
    - { port: 8083, targetPort: api, name: api }
  selector: { app: debezium }
