apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: app
  labels:
    app: django
    tier: backend-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: PLACEHOLDER_ECR_REPO/neuralops-django:latest # patched per-overlay
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: django-config
            - secretRef:
                name: django-secrets
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
              httpHeaders:
                - name: Host
                  value: adinath.site
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
              httpHeaders:
                - name: Host
                  value: adinath.site
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
